security:
    encoders:
        # Our user class and the algorithm we'll use to encode passwords
        # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
        Sulmi\ProductBundle\Entity\UserEntity: bcrypt

    providers:
        # in this example, users are stored via Doctrine in the database
        # To see the users at src/AppBundle/DataFixtures/ORM/LoadFixtures.php
        # To load users from somewhere else: http://symfony.com/doc/current/cookbook/security/custom_provider.html
        database_users:
            entity: { class: SulmiProductBundle:UserEntity, property: name }

    # http://symfony.com/doc/current/book/security.html#firewalls-authentication
    firewalls:
        secured_area:
            # this firewall applies to all URLs
            pattern: ^/
            methods: ~
            # but the firewall does not require login on every page
            # denying access is done in access_control or in your controllers
            anonymous: true

            # Reference: http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            form_login:
                check_path: security_login
                login_path: security_login
                # Reference: http://symfony.com/doc/current/cookbook/security/csrf_in_login_form.html
                csrf_token_generator: security.csrf.token_manager

            logout:
                # The route name the user can go to in order to logout
                path: security_logout
                # The name of the route to redirect to after logging out
                target: sulmi_product_homepage_lang

    access_control:
        # this is a catch-all for the admin area
        # additional security lives in the controllers
        - { path: '^/(%app_locales%)/sulmi-product/product/admin', roles: ROLE_ADMIN }
        - { path: '^/(%app_locales%)/sulmi-product/category/admin', roles: ROLE_ADMIN }
        - { path: '^/(%app_locales%)/sulmi-product/productmedia', roles: ROLE_ADMIN }
        - { path: '^/(%app_locales%)/sulmi-product/product/userentity/users/list/*', roles: ROLE_ADMIN }
#        - { path: '^/(%app_locales%)/sulmi-product/product/userentity/users/list/new', roles: ROLE_ADMIN }
#        - { path: '^/(%app_locales%)/sulmi-product/admin-product', roles: ROLE_ADMIN, methods: [POST, PUT, GET] }
#        - { path: '^/(%app_locales%)/sulmi-product/product', roles: ROLE_USER }
